### ISSUE TITLE
jsonlite::rbind_pages has plyr dependency 

### ISSUE THREAD

**Issue by johnWilshire** [MapofLife/rstoat#1]
`jsonlite::rbind_pages` has a 'Suggests' dependency for the `plyr` package.
We should replace this with `do.call(rbind.data.frame, results)`.

See here: 
https://github.com/MapofLife/rstoat/blob/fedee12ab28c5b4b0505570223d00ac12a730bb2/R/datasets.R#L114

**Comment by rich9100** [comment]
Made this change in https://github.com/MapofLife/rstoat/commit/7809f1e3c772492a10e4e8b02210405e6bddea7f
